# This scrape config instructs Prometheus to scrape the http://localhost:8080/actuator/prometheus endpoint on the host.docker.internal:8080 address every 3 seconds.
#  The application label is used to identify the application in Prometheus.

scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Prometheus and Grafana Application'
